name: Re g_data folder

on:
  workflow_dispatch:
    inputs:
      warning:
        description: 'WARNING: This will DELETE ALL files inside g_data/ folder. are you sure?'
        required: false
        default: 'show warning before proceeding'

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Remove g_data folder and recreate it
        run: |
          rm -rf g_data
          mkdir g_data

      - name: Commit and push empty folder
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add g_data
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Empty g_data folder [skip ci]"
            git pull --rebase origin "${{ github.ref_name }}"
            git push origin HEAD:"${{ github.ref_name }}"
            echo "g_data folder cleared"
          fi
